ALTER TABLE characters
ADD COLUMN IF NOT EXISTS archetype VARCHAR(255),
ADD COLUMN IF NOT EXISTS goals TEXT,
ADD COLUMN IF NOT EXISTS motivations TEXT,
ADD COLUMN IF NOT EXISTS fears TEXT,
ADD COLUMN IF NOT EXISTS hobbies TEXT;

ALTER TABLE layers
ADD COLUMN IF NOT EXISTS type VARCHAR(50),
ADD COLUMN IF NOT EXISTS photo_prompt TEXT,
ADD COLUMN IF NOT EXISTS video_prompt TEXT,
ADD COLUMN IF NOT EXISTS audio_prompt TEXT,
ADD COLUMN IF NOT EXISTS text_prompt TEXT;