from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c87a652ed9b'
down_revision = 'None'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
